apps/companies/urls.py
from django.urls import path

# # Importing views
from .views.ContractsList import ContractsList
from .views.newEmployee import newEmployee
from .views.EditEmployee import EditEmployee
from .views.editContract import editContract
from .views.newContract import newContract
from .views.charges import charges
from .views.Costcenter import Costcenter
from .views.workplace import workplace
from .views.headquarters import headquarters
from .views.hiring import hiring
# from .views.laborcertification import laborcertification
from .views.loginweb import loginweb
from .views.payrollsheet import payrollsheet
from .views.assetsview import assetsview
from .views.birthday import birthday
from .views.workcertificate import workcertificate
from .views.bank_list import bank_list
from .views.settlementlist import settlementlist
from .views.payrollaccumulations import payrollaccumulations
from .views.abstractconcept import abstractconcept

# # Accounting views
from .views.PayrollProvision import payrollprovision
from .views.externalreport import externalreport
from .views.dian import dian

# # Payroll News views
from .views.loans import loans
from .views.disabilities import disabilities
from .views.vacation import vacation, vacation_general, vacation_balance, vacation_request

from .views.index import index

from .views.accountinggroup import accountinggroup



urlpatterns = [
    # ## Employee Contract URLs
    path('employees/contract/', ContractsList.startCompanies, name='startcompanies'),
    path('employees/excel0', ContractsList.exportar_excel0, name='exportar_excel0'),
    path('employees/excel1', ContractsList.exportar_excel1, name='exportar_excel1'),
    path('employees/excel2', ContractsList.exportar_excel2, name='exportar_excel2'),

    #hiring new items 
    path('employees/hiring/', hiring.hiring, name='hiring'),
    path('employees/hiring/employee', hiring.hiring_employee, name='hiring_employee'),
    
    path('employees/hiring/contract/<str:idempleado>', hiring.hiring_contract, name='hiring_contract'),
    
    #path('employees/hiring/employee', hiring.process_forms_employee, name='process_forms_employee'),
    
    # ## Employee Management URLs
    # path('employees/new/employee', newEmployee.newEmployee, name='newemployee'),
    # path('employees/edit/employee', EditEmployee.EditEmployeeSearch, name='editemployeesearch'),
    path('employees/edit/employee/<str:idempleado>', EditEmployee.EditEmployeeVisual, name='editemployeevisual'),

    # ## Contract Management URLs
    # path('employees/new/contract', newContract.newContractVisual, name='newcontractvisual'),
    # path('employees/new/contract/<str:idempleado>', newContract.newContractCreater, name='newcontractcreater'),
    path('employees/edit/contract/<str:idempleado>', editContract.EditContracVisual, name='editcontracvisual'),

    # ## Work Certificate URLs
    path('employees/workcertificate/', workcertificate.workcertificate, name='workcertificate'),
    path('employees/workcertificate/generar_pdf/', workcertificate.generateworkcertificate, name='generateworkcertificate'),
    path('employees/workcertificate/generar_pdf/<int:idcert>', workcertificate.certificatedownload, name='certificatedownload'),

    # ## Birthday URL
    path('employees/birthday/', birthday.birthday_view, name='birthdayview'),

    # ## Asset Views URLs
    path('employees/views/contract/', assetsview.contractview, name='contractview'),
    path('employees/views/employee/', assetsview.resumeview, name='resumeview'),

    # ## Parameters URLs
    path('parameters/charges', charges.charges, name='charges'),
    path('parameters/charges/activate/<int:id>/', charges.toggle_charge_active_status, {'activate': True}, name='chargeactivate'),
    path('parameters/charges/deactivate/<int:id>/', charges.toggle_charge_active_status, {'activate': False}, name='chargedeactivate'),

    path('parameters/Cost/center', Costcenter.Costcenter, name='costcenter'),
    path('parameters/workplace', workplace.workplace, name='workplace'),
    path('parameters/headquarters', headquarters.headquarters, name='headquarters'),
    path('parameters/accountin',accountinggroup.accountinggroup , name='accountinggroup'),

    # ## Accounting URLs
    path('accounting/payroll/provision/', payrollprovision.payrollprovision, name='payrollprovision'),
    path('accounting/payroll/provision/download/', payrollprovision.payrollprovisiondownload_excel, name='payrollprovisiondownload_excel'),
    path('accounting/contributions/provision/', payrollprovision.contributionsprovision, name='contributionsprovision'),
    path('accounting/contributions/provision/download/', payrollprovision.contributionsprovisiondownload_excel, name='contributionsprovisiondownload_excel'),
    path('accounting/external/report/', externalreport.externalreport, name='externalreport'),
    path('accounting/external/report/download/', externalreport.download_excel_report, name='download_excel_report'),
    path('accounting/dian/certificate/', dian.viewdian, name='viewdian'),
    path('accounting/dian/certificate/download/<str:idingret>/', dian.viewdian_download, name='viewdian_download'),

    # ## Payroll URLs
    # path('payroll/labor/certification/', laborcertification.laborcertification, name='laborcertification'),
    path('payroll/sheet/', payrollsheet.payrollsheet, name='payrollsheet'),
    path('payroll/sheet/download/<int:idnomina>/<int:idcontrato>/', payrollsheet.generatepayrollcertificate, name='generatepayrollcertificate'),
    path('payroll/sheet/send/<int:idnomina>/<int:idcontrato>/', payrollsheet.unique_mail, name='unique_mail'),
    path('payroll/summary/download/<int:idnomina>/', payrollsheet.generatepayrollsummary, name='generatepayrollsummary'),
    path('payroll/summary/download/<int:idnomina>/all/', payrollsheet.generatepayrollsummary2, name='generatepayrollsummary2'),
    path('payroll/bank/list/get/', bank_list.bank_list_get, name='bank_list_get'),
    path('payroll/bank/list/file/<int:idnomina>/', bank_list.bank_file, name='bank_file'),
    path('payroll/settlement/list/', settlementlist.settlementlist, name='settlementlist'),
    path('payroll/settlement/download/<int:idliqui>/', settlementlist.settlementlistdownload, name='settlementlistdownload'),
    path('payroll/payroll/accumulations/', payrollaccumulations.payrollaccumulations, name='payrollaccumulations'),
    path('payroll/payroll/accumulations/download/', payrollaccumulations.descargar_excel_empleados, name='descargar_excel_empleados'),
    path('payroll/payroll/abstract/concept/', abstractconcept.abstractconcept, name='abstractconcept'),

    # ## Payroll News URLs
    path('payroll/new/loans/', loans.loans, name='loans'),
    path('payroll/new/loans/edit/', loans.edit_loans, name='edit_loans'),
    path('payroll/new/disabilities/', disabilities.disabilities, name='disabilities'),
    path('payroll/new/disabilities/edit/', disabilities.edit_disabilities, name='edit_disabilities'),
    path('payroll/new/disabilities/entity/', disabilities.get_entity, name='get_entity'),
    path('payroll/vacation/historical', vacation.vacation, name='vacation'),
    path('payroll/vacation/general/', vacation_general.vacation_general, name='vacation_general'),
    path('payroll/vacation/general/data/', vacation_general.get_novedades, name='get_novedades'),
    path('payroll/vacation/balance/', vacation_balance.vacation_balance, name='vacation_balance'),
    path('payroll/vacation/balance/download/', vacation_balance.vacation_balance_download, name='vacation_balance_download'),
    path('payroll/vacation/request/', vacation_request.vacation_request, name='vacation_request'),
    path('payroll/vacation/request/get/', vacation_request.get_vacation_details, name='get_vacation_details'),
    path('payroll/vacation/request/acction/', vacation_request.get_vacation_acction, name='get_vacation_acction'),

    # ## Mass Email URL
    path('payroll/sheet/massive/mail/', payrollsheet.massive_mail, name='massivemail'),

    # ## Security URLs
    path('security/user/', loginweb.loginweb, name='loginweb'),

    ## Admin Login URL (commented out)
    
    ## Index URL
    path('', index.index_companies, name='index_companies'),
]


urlhtmxpatterns =[
    path('parameters/cost/center/add', Costcenter.costcenter_modal, name='costcenter_modal'),
    path('parameters/charges/add', charges.charges_modal, name='charges_modal'),
    path('parameters/accountin/add',accountinggroup.accountinggroup_modal , name='accountinggroup_modal'),
    path('parameters/workplace/add', workplace.workplace_modal, name='workplace_modal'),
    path('parameters/headquarters/add', headquarters.headquarters_modal, name='headquarters_modal'),

]

urlpatterns += urlhtmxpatterns  

urlunpolypatterns =[
    
    path('payroll/new/disabilities/modal', disabilities.disabilities_modal, name='disabilities_modal'),
    path('payroll/new/disabilities/modal/edit', disabilities.disabilities_modal_edit, name='disabilities_modal_edit'),

]

urlpatterns += urlunpolypatterns  

nomiweb/urls.py
from django.contrib import admin
from django.urls import path ,include
from apps.login.views import custom_400 ,custom_403,custom_404 ,custom_500
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

# Importa Django Debug Toolbar solo si DEBUG está activado
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', include(('apps.login.urls', 'login'))),
    path('accounts/', include('allauth.urls')),
    path('', include('allauth.socialaccount.urls')),
    #path('contable/', include(('apps.payroll.urls', 'payroll'))),
    path('employees/', include(('apps.employees.urls', 'employees'))),
    path('companies/', include(('apps.companies.urls', 'companies'))),
    path('admin/', include(('apps.administrator.urls', 'admin'))),
    path('payroll/', include(('apps.payroll.urls', 'payroll'))),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Si DEBUG está activado, agrega las URLs de Django Debug Toolbar
if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

#handler400 = custom_400  # Configura la vista custom_400 para manejar el error 400
#handler403 = custom_403  # Configura la vista custom_403 para manejar el error 403
handler404 = 'apps.login.views.custom_404' # Configura la vista custom_404 para manejar el error 404
handler500 = 'apps.login.views.custom_500'  # Configura la vista custom_500 para manejar el error 500

apps/companies/forms/AbstractConceptForm.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column ,Button
from apps.common.models import Contabgrupos , Nomina , Contratosemp



CONCEPT_CHOICES = [
        ('', '---------------'),
        ('1', 'Concepto 1'),
        ('2', 'Concepto 2'),
        ('3', 'Concepto 3'),
        # Agrega más opciones según sea necesario
    ]


MONTH_CHOICES = [
    ('', '---------------'),
    ('ENERO', 'Enero'),
    ('FEBRERO', 'Febrero'),
    ('MARZO', 'Marzo'),
    ('ABRIL', 'Abril'),
    ('MAYO', 'Mayo'),
    ('JUNIO', 'Junio'),
    ('JULIO', 'Julio'),
    ('AGOSTO', 'Agosto'),
    ('SEPTIEMBRE', 'Septiembre'),
    ('OCTUBRE', 'Octubre'),
    ('NOVIEMBRE', 'Noviembre'),
    ('DICIEMBRE', 'Diciembre'),
]





YEAR_CHOICES = [
    ('', '---------------'),
    ('2023', '2023'),
    ('2024', '2024'),
    ('2025', '2025'),
    # Agrega más opciones según sea necesario
]

EMPLOYEE_CHOICES = [
    ('', '---------------'),
    ('1', 'Pilar Castañeda'),
    ('2', 'Iván Paez')
]

COST_CENTER_CHOICES = [
    ('', '---------------'),
    ('1', 'Centro de Costos 1'),
    ('2', 'Centro de Costos 2')
]


class AbstractConceptForm(forms.Form):
    

    
    sconcept = forms.ChoiceField(choices=CONCEPT_CHOICES, label='Concepto' , required=False,widget=forms.Select(attrs={'data-control': 'select2'}))
    
    payroll = forms.ChoiceField(choices=EMPLOYEE_CHOICES, label='Nómina' , required=False,widget=forms.Select(attrs={'data-control': 'select2'}))
    
    employee = forms.ChoiceField(choices=EMPLOYEE_CHOICES, label='Empleado' , required=False,widget=forms.Select(attrs={'data-control': 'select2'}))
    
    month = forms.ChoiceField(choices=MONTH_CHOICES, label='Mes Acumular' , required=False)
    
    year = forms.ChoiceField(choices=YEAR_CHOICES, label='Año Acumular' , required=False)
    
    def clean(self):
        cleaned_data = super().clean()
        filled_fields_count = sum(1 for field in self.fields if cleaned_data.get(field))
        
        if filled_fields_count < 2:
            raise forms.ValidationError('Debe Seleccionar al menos dos campos.' )

        return cleaned_data
    
    def __init__(self, *args, **kwargs):
        idempresa = kwargs.pop('idempresa', None)
        super().__init__(*args, **kwargs)

        # Actualizar choices dinámicamente
        self.fields['sconcept'].choices = [('', '----------')] + [(concepto, concepto) for concepto in Nomina.objects.filter(idnomina__id_empresa = idempresa ).values_list('idconcepto__nombreconcepto', flat=True).distinct().order_by('idconcepto__nombreconcepto') ]
        self.fields['payroll'].choices = [('', '----------')] + [(idnomina, nombrenomina) for nombrenomina, idnomina in Nomina.objects.filter(idnomina__id_empresa = idempresa ).select_related('idnomina').values_list('idnomina__nombrenomina', 'idnomina').distinct().order_by('-idnomina')]
        self.fields['employee'].choices = [('', '----------')] + [(idempleado, f"{papellido} {sapellido} {pnombre} {snombre} ") for idempleado, pnombre, snombre, papellido, sapellido in Contratosemp.objects.filter(id_empresa = idempresa ).values_list('idempleado', 'pnombre', 'snombre', 'papellido', 'sapellido').distinct().order_by('papellido')]
        #self.fields['month'].choices = [('', '----------')] + [(mes, mes) for mes in range(1, 13)]
        #self.fields['year'].choices = [('', '----------')] + [(ano, ano) for ano in Nomina.objects.values_list('idnomina__anoacumular__ano', flat=True).distinct().order_by('-idnomina__anoacumular__ano')]
        
        self.fields['year'] = forms.ChoiceField(
            choices=[('', '----------')] + [(ano, ano) for ano in Nomina.objects.values_list('idnomina__anoacumular__ano', flat=True).distinct().order_by('-idnomina__anoacumular__ano')],
            label='Año Acumular',
            required=False,
            widget=forms.Select(attrs={
                'data-control': 'select2',
                'data-tags': 'true',
                'data-hide-search': 'true',
                'class': 'form-select',
            })
        )
        
        self.fields['month'] = forms.ChoiceField(
            choices= MONTH_CHOICES ,
            required=False,
            label='Mes Acumular',
            widget=forms.Select(attrs={
                'data-control': 'select2',
                'data-tags': 'true',
                'data-hide-search': 'true',
                'class': 'form-select',
            })
        )

        # self.fields['cost_center'] = forms.ChoiceField(choices=[('', '----------')] + [(costo.idcosto, costo.nomcosto) for costo in Costos.objects.all()], label='Centro de Costos', required=False,)
        # self.fields['city'] = forms.ChoiceField(choices=[('', '----------')] + [(ciudad.idciudad,  f"{ciudad.ciudad} - {ciudad.departamento}" ) for ciudad in Ciudades.objects.all().order_by('ciudad')[:10]], label='Lugar de trabajo' , required=False, widget=forms.Select(attrs={'data-control': 'select2'}))

        self.helper = FormHelper()
        self.helper.form_id = 'Filto_conceptos'
        self.helper.layout = Layout(
            Row(
                Column('sconcept', css_class='form-group mb-0'),
                Column('payroll', css_class='form-group mb-0'),
                css_class='row'
            ),
            Row(
                Column('employee', css_class='form-group mb-0'),
                Column('month', css_class='form-group mb-0'),
                Column('year', css_class='form-group mb-0'),
                css_class='row'
            ),
            Row(
                Column(
                    Submit('submit', 'Filtrar', css_class='btn btn-light-info w-100'),  # Botón de envío
                    css_class='col-md-6'
                ),
                Column(
                    Button('button', 'Limpiar filtrado', css_class='btn btn-light-primary w-100', id='my-custom-button'),  # Botón sin acción de envío
                    css_class='col-md-6'
                ),
                css_class='row'
            ),
            
            
        )
    
    

templates/companies/NewEmployee.html
{% extends 'base/base.html' %} 

{% load crispy_forms_tags %}

{% block title %} 
Nomiweb.co - Portal Empresas -Nuevo Empleado 
{% endblock %} 

{% block css %} 
{% endblock %} 

{% block titulo2 %} 
Nuevo Empleado
{% endblock %}


{% block cssarch %}
{% endblock %}

{% block content %}
    <main class="flex-grow-1">
        {% crispy form %}
    </main>
{% endblock %}

{% block js %}

{% endblock %}

templates/companies/newContractCreate.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Nomiweb.co - Portal Empresas - Nuevo Empleado {% endblock %}

{% block css %} 
<style>
    #backButton {
        margin-left: auto;
        display: block;
    }
</style>
{% endblock %}

{% block cssarch %}
{% endblock %}

{% block sub_titulo1 %} 
    empleados
{% endblock %}

{% block  sub_titulo2%} 
    Nuevo Contrato
{% endblock %}

{% block titulo2 %} 
    Nuevo Contrato
{% endblock %}

{% block content %}
<div style="display: flex;">
    <button class="btn btn-light-primary" id="backButton">
        Regresar
    </button>
</div>

<main class="flex-grow-1 content">  
    {% crispy form %}
</main>



{% endblock %}

{% block js %}
<script>
    document.getElementById('backButton').addEventListener('click', function() {
        window.history.back();
    });
</script>
{% endblock %}

templates/companies/payrollaccumulations.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Nomiweb.co - Portal Empresas -nomina
{% endblock %}


{% block navbar %}
    {% if user.is_admin %}
        {% include 'base/navbar_administrator.html' %} 
    {% elif user.is_company %}
        {% include 'base/navbar_companies.html' %}    
    {% elif user.is_accountant %}
        {% include 'base/navbar_payroll.html' %}   
    {% elif user.is_employee %}
        {% include 'base/navbar_employees.html' %}   
    {% else %}
        <p>No tienes un rol asignado.</p>
    {% endif %}               
{% endblock %}

{% block css %}
/* Estilo para el botón con indicador */
.btn-light-info {
    position: relative;
    overflow: hidden;
    transition: all 0.3s ease;
}

/* Estilo para el indicador de carga */
[data-kt-indicator="on"] .indicator-label {
    opacity: 0;
}

[data-kt-indicator="on"] .indicator-progress {
    display: flex;
}

.indicator-label {
    display: inline-block;
    transition: opacity 0.3s ease;
}

.indicator-progress {
    display: none;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    align-items: center;
    justify-content: center;
}

.spinner-border {
    width: 1rem;
    height: 1rem;
    border-width: 0.2em;
}

.asteriskField {
    color: red !important;
}
{% endblock %}

{% block sub_titulo1 %} 
    Nomina
{% endblock %}

{% block sub_titulo2 %} 
    Acumulados de Nomina
{% endblock %}

{% block titulo2 %} 
    Filtrados
{% endblock %}

{% block content %}

<div class="container">
    <div class="card shadow-sm">
        <div class="card-header">
            <h3 class="card-title">Acumulados de Nomina - Filtros </h3>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
    <br>
    <br>
    <div class="separator  border-0 my-10"></div>


    {% if compects %}
        <div class="table-responsive">
            <table id="tabla-liquidacion" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Docidentidad</th>
                        <th>Empleado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for compect in compects %}
                        <tr>
                            <td>{{ compect.documento }}</td>
                            
                            <td>
                                
                                {{ compect.empleado }}  Contrato {{ compect.contrato }}

                                 <table class="table table-sm inner-table">
                                    <thead>
                                        <tr class="fw-semibold fs-6 text-gray-800 border-bottom border-gray-200" >
                                            <th>Concepto</th>
                                            <th>Nombre</th>
                                            <th>Cantidad</th>
                                            <th>Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for concepto in compect.data %}
                                            <tr>
                                                <td>{{ concepto.idconcepto }}</td>
                                                <td class="text-start">{{ concepto.nombreconcepto }}</td>
                                                <td class="text-end" >{{ concepto.cantidad }}</td>
                                                <td class="text-end">{{ concepto.valor }}</td>
                                            </tr>
                                        {% empty %}
                                            <tr>
                                                <td colspan="4">No hay conceptos para mostrar</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table> 
                            
                            </td>


                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">No se encontraron resultados</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-primary" role="alert">
            <h4 class="alert-heading">¡Atención!</h4>
            <p>Parece que la lista está vacía en este momento. Por favor, seleccione una nómina para visualizar los datos correspondientes.</p>
            <hr>
            <p class="mb-0">Agradecemos su colaboración para completar esta información.</p>
        </div>
    {% endif %}

    

</div>

<div class="modal fade" id="loadingModal" tabindex="-1" aria-labelledby="loadingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <div class="spinner-border" role="status">
                    <span class="sr-only">Cargando...</span>
                </div>
                <p>Cargando...</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}

<script>
    $(document).ready(function() {
        $('#Filter_report').on('submit', function() {
            $('#loadingModal').modal('show');
        });
    });
</script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var clearButton = document.getElementById('button-id-button');
        if (clearButton) {
            clearButton.addEventListener('click', function() {
                var form = document.getElementById('Filter_report');
                if (form) {
                    form.reset();
                    // Limpiar los campos de fecha manualmente
                    var dateInputs = form.querySelectorAll('input[type="date"]');
                    dateInputs.forEach(function(input) {
                        input.value = '';
                    });
                    // Opcional: Reconfigurar select2 si se usa
                    $(form).find('select[data-control="select2"]').val(null).trigger('change');
                    $('#loadingModal').modal('show');
                    // Recargar la página para eliminar el POST
                    window.location.href = window.location.pathname;
                }
            });
        }
    });
</script>

<script>
    $(document).ready(function() {
        // Inicializar DataTable
        var table = $('#tabla-liquidacion').DataTable({
            language: {
                "decimal": "",
                "emptyTable": "No se encontraron registros coincidentes",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ entradas",
                "infoEmpty": "Mostrando 0 a 0 de 0 entradas",
                "infoFiltered": "(filtrado de _MAX_ entradas totales)",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "No se encontraron registros coincidentes",
                "paginate": {
                    "first": "Primero",
                    "last": "Último",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": activar para ordenar la columna ascendente",
                    "sortDescending": ": activar para ordenar la columna descendente"
                }
            },
            dom: 'Bfrtip',
            buttons: [
                {
                    text: 'Descargar Acumulados',
                    action: function (e, dt, node, config) {
                        // Activar indicador
                        $(node).attr("data-kt-indicator", "on");

                        $.ajax({
                            url: '{% url "companies:descargar_excel_empleados" %}', // Reemplaza "handle_post_request" con el nombre de tu URL
                            type: 'POST',
                            data: {
                                'csrfmiddlewaretoken': '{{ csrf_token }}', // Incluye el token CSRF
                                'start_date': $('#id_start_date').val(),
                                'end_date': $('#id_end_date').val(),
                                'employee': $('#id_employee').val(),
                                'cost_center': $('#id_cost_center').val(),
                                'city': $('#id_city').val()
                            },
                            xhrFields: {
                                responseType: 'blob'
                            },
                            success: function(response) {
                                var url = window.URL.createObjectURL(new Blob([response]));
                                var a = document.createElement('a');
                                a.href = url;
                                a.download = 'filtered_data.xlsx';
                                document.body.appendChild(a);
                                a.click();
                                window.URL.revokeObjectURL(url);
                                
                                // Desactivar indicador
                                $(node).removeAttr("data-kt-indicator");
                            },
                            error: function(xhr, status, error) {
                                console.error('Error:', error);
                                alert('Error al realizar el Documento');
                                
                                // Desactivar indicador
                                $(node).removeAttr("data-kt-indicator");
                            }
                        });
                    },
                    className: 'btn btn-light-info',
                    attr: {
                        id: 'kt_button_1'
                    }
                }
            ],

            
            order: [[0, 'asc']], // Cambia el índice de la columna por defecto para ordenar
            pageLength: 10
        });

        // Manejar clic en el botón para activar el indicador
        $(document).on('click', '#kt_button_1', function() {
            var button = $(this);

            // Activar indicador
            button.attr("data-kt-indicator", "on");

            // Desactivar indicador después de 3 segundos o cuando la solicitud se completa
            setTimeout(function() {
                button.removeAttr("data-kt-indicator");
            }, 3000);
        });
    });
</script>

{% endblock %}