apps/payroll/urls.py
from django.urls import path
from .views.index import index
from .views.payroll import payroll , payroll_automatic_systems
from .views.flat  import flat 
from .views.electronic_payroll import electronic_payroll
from .views.loans import loans
from .views.parameters import parameters
from .views.pruebas import pruebas

# afsa fsa asfad 

urlpatterns = [
    path('home/', index.index_payroll, name='index_payroll'),
    path('payroll/', payroll.payroll, name='payroll'),
    path('payroll/<str:id>', payroll.payrollview, name='payrollview'),


    #electronic_payroll
    path('payroll/electronic_payroll/', electronic_payroll.electronic_payroll_container, name='nomina_electronica'),
    path('payroll/detail_electronic_payroll/<int:pk>', electronic_payroll.electronic_payroll_detail, name='detalle_nomina_electronica'),
    path('payroll/generate_detail_electronic_payroll/<int:pk>', electronic_payroll.electronic_payroll_generate_refactor, name='generar_detalle_electronica_ref'),
    path('payroll/electronic_payroll_regenerate/<int:pk>', electronic_payroll.electronic_payroll_regenerate, name='generar_detalle_individual'),
    path('payroll/electronic_payroll_validate_send/<int:pk>', electronic_payroll.electronic_payroll_validate_send, name='enviar_nomina_electronica'),
    path('payroll/electronic_payroll_validate_masive_send/<int:pk>', electronic_payroll.electronic_payroll_validate_masive_send, name='enviar_nomina_electronica_masiva'),
    path('payroll/electronic_payroll_detail_view/<int:pk>', electronic_payroll.electronic_payroll_detail_view, name='ver_nomina_electronica_detalle'),
    
    #loans
    path('loans', loans.employee_loans, name='loans_list'),
    path('loans_detail/<int:pk>', loans.detail_employee_loans, name='loans_detail'),
    path('api_detail_payroll_loan/<int:pk>', loans.api_detail_payroll_loan, name='api_loans_detail'),

    ## plano 
    path('flat/<int:id>', flat.flat , name='flat'),
    path('document/', flat.document, name='document_flat'),
    
    #parametros
    path('parameters/bancks', parameters.banks, name='banks'),
    path('parameters/holidays', parameters.holidays, name='holidays'),
    path('parameters/entities', parameters.entities, name='entities'),
    path('parameters/fixed', parameters.fixed, name='fixed'),
    path('parameters/annual', parameters.annual, name='annual'),
    path('parameters/concepts', parameters.concepts, name='concepts'),
    


    

]


urlhtmxpatterns =[
    
    
    path('parameters/concepts/add', parameters.concepts_add, name='concepts_add'),
    path('parameters/concepts/check/code', parameters.check_code, name='check_code'),
    
    
    

]

urlpatterns += urlhtmxpatterns  



urlunpolypatterns =[
    path('payroll/<int:id>/<int:idnomina>/modals/add', payroll.payroll_modal, name='payroll_modal'),
    path('payroll/modals/edit', payroll.payroll_edit, name='payroll_edit'),
    path('payroll/form/modals/create', payroll.payroll_create, name='payroll_create'),
    path('payroll/form/modals/delete', payroll.payroll_delete, name='payroll_delete'),
    path('payroll/form/calculate/<int:id>', payroll.payroll_calculate, name='payroll_calculate'),
    path('payroll/form/concept/', payroll.payroll_concept_info, name='payroll_concept_info'),
    path('payroll/form/concept/edit', payroll.payroll_info_edit, name='payroll_info_edit'),
    
    ## add employee
    path('payroll/<int:idnomina>/payroll_general', payroll.payroll_general, name='payroll_general'),
    path('payroll/<int:idnomina>/payroll_general/data', payroll.payroll_general_data, name='payroll_general_data'),
    
    # pruebas 
    path('items/', pruebas.index_item, name='index_item'),
    path('items/add/', pruebas.item_modal, name='item_modal'),
    path('items/add/modal', pruebas.add_item, name='add_item'),
    
    # segundas pruebas 
    path('my_form/', pruebas.my_form, name='my_form'),
    path('validate_number/', pruebas.get_multiplicador, name='get_multiplicador'),
    
    
    
    ## sitemas automaticos 
    
    path('payroll/automatic_systems/<int:type_payroll>/<int:idnomina>/modal', payroll_automatic_systems.automatic_systems, name='automatic_systems'),
    
    
    ## flat
    path('flat/modal', flat.flat_modal, name='flat_modal'),
    
    
]

urlpatterns += urlunpolypatterns  

nomiweb/urls.py
from django.contrib import admin
from django.urls import path ,include
from apps.login.views import custom_400 ,custom_403,custom_404 ,custom_500
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

# Importa Django Debug Toolbar solo si DEBUG está activado
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', include(('apps.login.urls', 'login'))),
    path('accounts/', include('allauth.urls')),
    path('', include('allauth.socialaccount.urls')),
    #path('contable/', include(('apps.payroll.urls', 'payroll'))),
    path('employees/', include(('apps.employees.urls', 'employees'))),
    path('companies/', include(('apps.companies.urls', 'companies'))),
    path('admin/', include(('apps.administrator.urls', 'admin'))),
    path('payroll/', include(('apps.payroll.urls', 'payroll'))),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Si DEBUG está activado, agrega las URLs de Django Debug Toolbar
if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

#handler400 = custom_400  # Configura la vista custom_400 para manejar el error 400
#handler403 = custom_403  # Configura la vista custom_403 para manejar el error 403
handler404 = 'apps.login.views.custom_404' # Configura la vista custom_404 para manejar el error 404
handler500 = 'apps.login.views.custom_500'  # Configura la vista custom_500 para manejar el error 500

apps/payroll/views/parameters/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column , HTML
from apps.common.models import Empresa , Contratos , Conceptosdenomina , NeSumatorias , Indicador  
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
TIPE_CHOICES = (
    ('', ''),
    ('EPS', 'EPS'),
    ('ARL', 'ARL'),
    ('CCF', 'CCF'),
    ('AFP', 'AFP'),
    ('PARAFISCALES', 'Parafiscales'),
)

TIPE_CONCEPTS = (
    ('', ''),
    ('1', 'Ingreso'),
    ('2', 'Deducción'),
)

TIPE_Formula = (
    ('', ''),
    (1, 'Si'),
    (0, 'No'),
)

class BanksForm(forms.Form):
    nombanco = forms.CharField(
        label='Nombre del Banco',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre del banco'})
    )
    codbanco = forms.IntegerField(
        label='Código del Banco',
        widget=forms.NumberInput(attrs={'placeholder': 'Ingrese el código del banco', 'class': 'form-control'})
    )
    codach = forms.IntegerField(
        label='Código ACH',
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Ingrese el código ACH', 'class': 'form-control'})
    )
    digchequeo = forms.IntegerField(
        label='Dígito de Chequeo',
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Ingrese el dígito de chequeo', 'class': 'form-control'})
    )
    nitbanco = forms.CharField(
        label='NIT del Banco',
        widget=forms.TextInput(attrs={'placeholder': 'Ingrese el NIT ', 'class': 'form-control'})
    )
    tamcorriente = forms.IntegerField(
        label='Tamaño Cuenta Corriente',
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Ingrese el tamaño', 'class': 'form-control'})
    )
    tamahorro = forms.IntegerField(
        label='Tamaño Cuenta de Ahorro',
        required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Ingrese el tamaño', 'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Configuración de Crispy Forms
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.enctype = 'multipart/form-data'

        # Diseño del formulario con Crispy Forms
        self.helper.layout = Layout(
            Row(
                Column('nombanco', css_class='form-group col-md-12 mb-0'),
                css_class='row'
            ),
            Row(
                Column('codbanco', css_class='form-group col-md-4 mb-0'),
                Column('codach', css_class='form-group col-md-4 mb-0'),
                Column('digchequeo', css_class='form-group col-md-4 mb-0'),
                css_class='row'
            ),
            Row(
                Column('nitbanco', css_class='form-group col-md-4 mb-0'),
                Column('tamcorriente', css_class='form-group col-md-4 mb-0'),
                Column('tamahorro', css_class='form-group col-md-4 mb-0'),
                css_class='row'
            ),
        )


class EntitiesForm(forms.Form):
    codigo = forms.CharField(
        label='Código',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el código'})
    )
    nit = forms.CharField(
        label='NIT',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el NIT de la entidad'})
    )
    entidad = forms.CharField(
        label='Nombre de la Entidad',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre de la entidad'})
    )
    tipoentidad = forms.ChoiceField(
        label='Tipo de Entidad',
        choices=TIPE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    codsgp = forms.CharField(
        label='Código SGP',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'SGP'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['tipoentidad'].widget.attrs.update({
            'data-control': 'select2',
            'data-hide-search': 'true' ,
            'class': 'form-select',
            'data-hide-search': 'true',
            'data-placeholder':'seleccione un tipo de entidad',
        })
        # Configuración de Crispy Forms
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'form_entitis'
        self.helper.enctype = 'multipart/form-data'

        # Diseño del formulario con Crispy Forms
        self.helper.layout = Layout(
            Row(
                Column('codigo', css_class='form-group col-md-6 mb-0'),
                Column('nit', css_class='form-group col-md-6 mb-0'),
                css_class='row'
            ),
            Row(
                Column('entidad', css_class='form-group col-md-5 mb-0'),
                Column('tipoentidad', css_class='form-group col-md-5 mb-0'),
                Column('codsgp', css_class='form-group col-md-2 mb-0'),
                css_class='row'
            ),
        )



class HolidaysForm(forms.Form):
    fecha = forms.DateField(
        label='Fecha',
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Seleccione la fecha'})
    )
    descripcion = forms.CharField(
        label='Descripción',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese una descripción breve'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Configuración de Crispy Forms
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'form_holidays'
        self.helper.enctype = 'multipart/form-data'

        # Diseño del formulario con Crispy Forms
        self.helper.layout = Layout(
            Row(
                Column('fecha', css_class='form-group col-md-6 mb-0'),
                Column('descripcion', css_class='form-group col-md-6 mb-0'),
                css_class='row'
            )
        )




class FixedForm(forms.Form):
    conceptofijo = forms.CharField(
        label='Concepto fijo',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el concepto fijo'})
    )
    valorfijo = forms.DecimalField(
        label='Valor fijo',
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el valor fijo'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Configuración de Crispy Forms
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.enctype = 'multipart/form-data'

        # Diseño del formulario con Crispy Forms
        self.helper.layout = Layout(
            Row(
                Column('conceptofijo', css_class='form-group col-md-6 mb-0'),
                Column('valorfijo', css_class='form-group col-md-6 mb-0'),
                css_class='row'
            )
        )
        
        
class AnnualForm(forms.Form):
    salariominimo = forms.DecimalField(
        label='Salario mínimo',
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el salario mínimo'})
    )
    auxtransporte = forms.DecimalField(
        label='Auxilio de transporte',
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el auxilio de transporte'})
    )
    uvt = forms.DecimalField(
        label='UVT',
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el valor de la UVT'})
    )
    ano = forms.IntegerField(
        label='Año',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el año'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Configuración de Crispy Forms
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.enctype = 'multipart/form-data'

        # Diseño del formulario con Crispy Forms
        self.helper.layout = Layout(
            Row(
                Column('salariominimo', css_class='form-group col-md-6 mb-0'),
                Column('auxtransporte', css_class='form-group col-md-6 mb-0'),
                css_class='row'
            ),
            Row(
                Column('uvt', css_class='form-group col-md-6 mb-0'),
                Column('ano', css_class='form-group col-md-6 mb-0'),
                css_class='row'
            )
        )
        

def validate_codigo_unique(value , id_empresa):
    if Conceptosdenomina.objects.filter(codigo = value ,id_empresa =  id_empresa ).exists():  # Aquí 'TuModelo' es el modelo donde se guardan los conceptos
        raise ValidationError(f"El código {value} ya está en uso. Por favor, ingrese un código único.")
    

class PayrollConceptsForm(forms.Form):
    nombreconcepto = forms.CharField(
        label='Nombre del Concepto',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre del concepto'})
    )
    multiplicadorconcepto = forms.DecimalField(
        label='Multiplicador',
        max_digits=4,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el multiplicador'})
    )
    
    tipoconcepto = forms.ChoiceField(
        label='Tipo de Concepto',
        choices=TIPE_CONCEPTS,
        widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Ingrese el tipo de concepto'})
    )
    
    formula = forms.ChoiceField(
        label='¿El concepto tiene fórmula?',

templates/payroll/partials/conceptsTables.html
<!-- payroll/partials/conceptsTables.html -->
<div class="huesped-form">
    <label for="nombre">Nombre:</label>
    <input type="text" name="nombre" required>

    <label for="apellido">Apellido:</label>
    <input type="text" name="apellido" required>

    <label for="email">Email:</label>
    <input type="email" name="email" required>
</div>

templates/payroll/partials/concepts_list.html
<div id="items-container">
<ol id="item-list"  class="list-group"> 
    {% for concepto in data.conceptos %}
        {% csrf_token %}
        <li id="item-{{ concepto.idn }}"  class="list-group-item">
            <div class="form-group row align-items-center" id="concepto-{{ concepto.idn }}">
                <div class="col-md-4 input-group-sm">
                    <select required class="form-select form-select-sm" data-control="select2" data-placeholder="Seleccione un Concepto" disabled id="select-{{ concepto.idn }}">
                        <option></option>
                        {% for id, nombre in data.conceptors %}
                            <option value="{{ id }}" {% if concepto.id == id %}selected{% endif %}>{{ nombre }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-md-2 input-group-sm">
                    <input type="text" class="form-control mb-2 mb-md-0" placeholder="Cantidad" value="{{ concepto.amount }}" disabled id="amount-{{ concepto.idn }}" />
                </div>
                <div class="col-md-3 input-group-sm" >
                    <input type="text" class="form-control mb-2 mb-md-0" placeholder="Valor" value="{{ concepto.value }}" disabled id="value-{{ concepto.idn }}" x-mask:dynamic="$money($input, '.', ',', 4)" />
                </div>

                <div class="col-md-3 d-flex align-items-center">
                    

                    <a  class="btn btn-icon btn-light-facebook me-2" 
                        up-target="#concepto-{{ concepto.idn }}"
                        up-emit="edit-concepto" 
                        data-idn="{{ concepto.idn }}">
                            <i class="fa-solid fa-pen-to-square fs-4"></i>
                    </a>

                    <a  class="btn btn-icon btn-light-success me-2" 
                        up-target="#concepto-{{ concepto.idn }}"
                        up-emit="save-concepto" 
                        data-idn="{{ concepto.idn }}" hidden>
                            <i class="fa-solid fa-save fs-4"></i>
                    </a>

                    <!-- Botón de eliminar -->
                    <button 
                    class="btn btn-icon btn-light-youtube me-2"
                    onclick="confirmDelete('{{ concepto.idn }}')"
                    
                    >
                        <i class="ki-duotone ki-trash fs-4">
                            <span class="path1"></span>
                            <span class="path2"></span>
                            <span class="path3"></span>
                            <span class="path4"></span>
                            <span class="path5"></span>
                        </i>
                    </button>
                </div>
            </div>
        </li>
    {% empty %}
        <li class="list-group-item">
            El empleado aun no tiene novedades de nomina 
        </li>
    {% endfor %}
    
</ol>
</div>

templates/payroll/partials/conceptsmodal.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" id="conceptsModal" name="conceptsModal" tabindex="-1" aria-labelledby="conceptsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-dialog-scrollable modal-lg">
        <div class="modal-content" id="modal-container">
            <div class="modal-header">
                <h5 class="modal-title" id="conceptsModalLabel">Nuevo Concepto</h5>
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()" >
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% crispy form %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal" onclick="closeModal()" >Cerrar</button>
                <button type="submit" form="form_concepts" class="btn btn-primary">Crear</button>
            </div>
        </div>
    </div>
</div>


<script>
    function closeModal() {
        var modal = bootstrap.Modal.getInstance(document.getElementById('conceptsModal'));
        var modalBackdrop = document.querySelector('.modal-backdrop');
        
        if (modal) {
            modal.hide(); // Cierra el modal
        }
        if (modalBackdrop) {
            modalBackdrop.remove(); // Elimina el fondo modal residual
        }

        // Limpiar los valores de los campos dentro del modal
        document.getElementById('conceptsModal').querySelectorAll('input, select').forEach(function(input) {
            if (input.type === 'checkbox' || input.type === 'radio') {
                input.checked = false;
            } else {
                input.value = '';
            }
        });

        // Limpiar los campos select2
        $('#id_tipoconcepto').val(null).trigger('change');
        $('#id_indicador').val(null).trigger('change');
        $('#id_grupo_dian').val(null).trigger('change');
        $('#id_formula').val(null).trigger('change');

        // Limpiar cualquier validación de los campos
        document.querySelectorAll('.is-invalid').forEach(function(element) {
            element.classList.remove('is-invalid');
        });
        document.querySelectorAll('.invalid-feedback').forEach(function(feedback) {
            feedback.innerHTML = '';
        });

        // Limpiar el contenido dentro del contenedor del modal
        document.getElementById('modal-container').innerHTML = '';
    }

    $(document).ready(function () {
        // Inicializa Select2 para los campos
        $('#id_tipoconcepto').select2({
            dropdownParent: $('#conceptsModal'),
            minimumResultsForSearch: -1,
            placeholder: "Seleccione un tipo de concepto",
        });

        $('#id_indicador').select2({
            dropdownParent: $('#conceptsModal'),
            placeholder: "Seleccione un Indicador",
            allowClear: true,
            closeOnSelect: false,
            multiple: true
        });

        $('#id_grupo_dian').select2({
            dropdownParent: $('#conceptsModal'),
            minimumResultsForSearch: -1,
            placeholder: "Seleccione un grupo DIAN",
            allowClear: true
        });

        $('#id_formula').select2({
            dropdownParent: $('#conceptsModal'),
            minimumResultsForSearch: -1,
            placeholder: "Seleccione una fórmula",
        });


    });

    // Escucha el evento 'htmx:afterRequest' para manejar la respuesta del servidor
    document.body.addEventListener('htmx:afterRequest', function(evt) {
        if (evt.detail.successful) {
            var response = evt.detail.xhr.responseText;
            
            // Verificar si la respuesta es un JSON con estado de éxito
            try {
                var responseJson = JSON.parse(response);
                console.log(responseJson);
                if (responseJson.status === 'success') {
                    var modal = bootstrap.Modal.getInstance(document.getElementById('conceptsModal'));
                    var modalBackdrop = document.querySelector('.modal-backdrop');
                    
                    if (modal) {
                        modal.hide(); // Cierra el modal después de una respuesta exitosa
                    }
    
                    if (modalBackdrop) {
                        modalBackdrop.remove(); // Elimina el fondo modal residual
                    }
    
                    // Mostrar el Swal de éxito
                    Swal.fire({
                        text: responseJson.message, // Mensaje de éxito
                        icon: "success",  
                        showConfirmButton: true,
                        confirmButtonText: "Ok",
                        customClass: {
                            confirmButton: "btn btn-primary"
                        }
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.reload();  // Recarga la página
                        }
                    });
    
                } else {
                    
                }
            } catch (e) {
                
            }
        }
    });


    
 
    
    
    
    


</script>

templates/payroll/partials/flat_modal.html
<!-- Bootstrap-styled modal -->
<div class="modal-content"  id="modal-content">
    <div class="modal-header">
        <h3 class="modal-title">Carga de Documento</h3>
        <!--begin::Close-->
        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" up-dismiss aria-label="Close">
            <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
        </div>
        <!--end::Close-->
    </div>   
    <div class="separator my-5"></div> 
    <!--begin::Input group-->        
    <div class="modal-body">
        <div class="container">

            <form id="upload-form" name="upload-form" method="POST" action="" enctype="multipart/form-data">
                <div class="mb-3">
                    {% csrf_token %}
                    <input  class="form-control form-control-sm" id="file-upload" name="file" type="file" />
                    <small id="fileHelp" class="form-text text-muted">
                        Solo se aceptan archivos de tipo Excel (.xlsx). <a href="{% url 'payroll:document_flat' %}" download>Descarga la plantilla aquí</a> si aún no la tienes.
                    </small>
                </div>
                <input type="hidden" id="hidden-field" name="hidden_field" value="valor_secreto" />
            </form>
        </div>

    </div>
    <div class="separator my-5"></div>
    <div class="modal-footer btn-group">
        <button type="button" class="btn btn-light-danger" up-dismiss>Close</button>
        <div style="width: 10px;"></div>
        <button type="submit" id="send-request" class="btn btn-primary">Cargar Archivo</button>
    </div>
</div>

templates/payroll/partials/payroll_automatic_systems.html
<div class="modal-content"  id="modal-content">
    <div class="modal-header">
        <h3 class="modal-title"> {{titulo}} </h3>
        <!--begin::Close-->
        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" up-dismiss aria-label="Close">
            <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
        </div>
        <!--end::Close-->
    </div>   
    <div class="separator my-5"></div> 
    <!--begin::Input group-->        
    <div class="modal-body">
        
        <div class="d-flex justify-content-center">
            <div class="col-md-12">
              <form method="post" action="{% url 'payroll:automatic_systems'  type_payroll  idnomina %}"  id="form_automatic" class="form-group">
                {% csrf_token %}
                
                <div class="row mb-3 justify-content-center">
                  <div class="col-md-6 input-group-sm text-center">
                    <label for="cost-center">
                      <input type="checkbox"  id="need-comment" name="need_comment" up-change="toggleCommentField()">
                      Cálculo por centro de costo?
                    </label>
                  </div>
                  <div class="col-md-6 input-group-sm text-center ">
                    <label for="no-cost-center">
                      <input type="checkbox" id="no-cost-center" name="no_cost_center">
                      Sin centro de costo?
                    </label>
                  </div>
                </div>
                <input type="hidden" name="idnomina" value={{idnomina}}>
                <br>
                <div class="row mb-3 justify-content-center" id="comment-field" style="display: none;">
                  <div class="col-md-12 input-group-sm text-center">
                    <select id="costos" name="costos" class="form-select form-select-sm" data-control="select2" data-placeholder="Seleccione un Centro de Costo">
                      <option value=""></option>
                      {% for centro in centros %}
                        <option value="{{ centro.idcosto }}">{{ centro.nomcosto }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
              </form>
            </div>
        </div>


    </div>
    <div class="separator my-5"></div>
    <div class="modal-footer btn-group">
        <button type="submit" class="btn btn-light-primary" form="form_automatic"  >Enviar</button>
        <div style="width: 10px;"></div>
        <button type="button" class="btn btn-light-danger" up-dismiss>Close</button>
    </div>
</div>

templates/payroll/partials/resultado.html
<p>El total calculado es: {{ total }}</p>