apps/companies/urls.py
from django.urls import path

# # Importing views
from .views.ContractsList import ContractsList
from .views.newEmployee import newEmployee
from .views.EditEmployee import EditEmployee
from .views.editContract import editContract
from .views.newContract import newContract
from .views.charges import charges
from .views.Costcenter import Costcenter
from .views.workplace import workplace
from .views.headquarters import headquarters
from .views.hiring import hiring
# from .views.laborcertification import laborcertification
from .views.loginweb import loginweb
from .views.payrollsheet import payrollsheet
from .views.assetsview import assetsview
from .views.birthday import birthday
from .views.workcertificate import workcertificate
from .views.bank_list import bank_list
from .views.settlementlist import settlementlist
from .views.payrollaccumulations import payrollaccumulations
from .views.abstractconcept import abstractconcept

# # Accounting views
from .views.PayrollProvision import payrollprovision
from .views.externalreport import externalreport
from .views.dian import dian

# # Payroll News views
from .views.loans import loans
from .views.disabilities import disabilities
from .views.vacation import vacation, vacation_general, vacation_balance, vacation_request

from .views.index import index

from .views.accountinggroup import accountinggroup



urlpatterns = [
    # ## Employee Contract URLs
    path('employees/contract/', ContractsList.startCompanies, name='startcompanies'),
    path('employees/excel0', ContractsList.exportar_excel0, name='exportar_excel0'),
    path('employees/excel1', ContractsList.exportar_excel1, name='exportar_excel1'),
    path('employees/excel2', ContractsList.exportar_excel2, name='exportar_excel2'),

    #hiring new items 
    path('employees/hiring/', hiring.hiring, name='hiring'),
    path('employees/hiring/employee', hiring.hiring_employee, name='hiring_employee'),
    
    path('employees/hiring/contract/<str:idempleado>', hiring.hiring_contract, name='hiring_contract'),
    
    #path('employees/hiring/employee', hiring.process_forms_employee, name='process_forms_employee'),
    
    # ## Employee Management URLs
    # path('employees/new/employee', newEmployee.newEmployee, name='newemployee'),
    # path('employees/edit/employee', EditEmployee.EditEmployeeSearch, name='editemployeesearch'),
    path('employees/edit/employee/<str:idempleado>', EditEmployee.EditEmployeeVisual, name='editemployeevisual'),

    # ## Contract Management URLs
    # path('employees/new/contract', newContract.newContractVisual, name='newcontractvisual'),
    # path('employees/new/contract/<str:idempleado>', newContract.newContractCreater, name='newcontractcreater'),
    path('employees/edit/contract/<str:idempleado>', editContract.EditContracVisual, name='editcontracvisual'),

    # ## Work Certificate URLs
    path('employees/workcertificate/', workcertificate.workcertificate, name='workcertificate'),
    path('employees/workcertificate/generar_pdf/', workcertificate.generateworkcertificate, name='generateworkcertificate'),
    path('employees/workcertificate/generar_pdf/<int:idcert>', workcertificate.certificatedownload, name='certificatedownload'),

    # ## Birthday URL
    path('employees/birthday/', birthday.birthday_view, name='birthdayview'),

    # ## Asset Views URLs
    path('employees/views/contract/', assetsview.contractview, name='contractview'),
    path('employees/views/employee/', assetsview.resumeview, name='resumeview'),

    # ## Parameters URLs
    path('parameters/charges', charges.charges, name='charges'),
    path('parameters/charges/activate/<int:id>/', charges.toggle_charge_active_status, {'activate': True}, name='chargeactivate'),
    path('parameters/charges/deactivate/<int:id>/', charges.toggle_charge_active_status, {'activate': False}, name='chargedeactivate'),

    path('parameters/Cost/center', Costcenter.Costcenter, name='costcenter'),
    path('parameters/workplace', workplace.workplace, name='workplace'),
    path('parameters/headquarters', headquarters.headquarters, name='headquarters'),
    path('parameters/accountin',accountinggroup.accountinggroup , name='accountinggroup'),

    # ## Accounting URLs
    path('accounting/payroll/provision/', payrollprovision.payrollprovision, name='payrollprovision'),
    path('accounting/payroll/provision/download/', payrollprovision.payrollprovisiondownload_excel, name='payrollprovisiondownload_excel'),
    path('accounting/contributions/provision/', payrollprovision.contributionsprovision, name='contributionsprovision'),
    path('accounting/contributions/provision/download/', payrollprovision.contributionsprovisiondownload_excel, name='contributionsprovisiondownload_excel'),
    path('accounting/external/report/', externalreport.externalreport, name='externalreport'),
    path('accounting/external/report/download/', externalreport.download_excel_report, name='download_excel_report'),
    path('accounting/dian/certificate/', dian.viewdian, name='viewdian'),
    path('accounting/dian/certificate/download/<str:idingret>/', dian.viewdian_download, name='viewdian_download'),

    # ## Payroll URLs
    # path('payroll/labor/certification/', laborcertification.laborcertification, name='laborcertification'),
    path('payroll/sheet/', payrollsheet.payrollsheet, name='payrollsheet'),
    path('payroll/sheet/download/<int:idnomina>/<int:idcontrato>/', payrollsheet.generatepayrollcertificate, name='generatepayrollcertificate'),
    path('payroll/sheet/send/<int:idnomina>/<int:idcontrato>/', payrollsheet.unique_mail, name='unique_mail'),
    path('payroll/summary/download/<int:idnomina>/', payrollsheet.generatepayrollsummary, name='generatepayrollsummary'),
    path('payroll/summary/download/<int:idnomina>/all/', payrollsheet.generatepayrollsummary2, name='generatepayrollsummary2'),
    path('payroll/bank/list/get/', bank_list.bank_list_get, name='bank_list_get'),
    path('payroll/bank/list/file/<int:idnomina>/', bank_list.bank_file, name='bank_file'),
    path('payroll/settlement/list/', settlementlist.settlementlist, name='settlementlist'),
    path('payroll/settlement/download/<int:idliqui>/', settlementlist.settlementlistdownload, name='settlementlistdownload'),
    path('payroll/payroll/accumulations/', payrollaccumulations.payrollaccumulations, name='payrollaccumulations'),
    path('payroll/payroll/accumulations/download/', payrollaccumulations.descargar_excel_empleados, name='descargar_excel_empleados'),
    path('payroll/payroll/abstract/concept/', abstractconcept.abstractconcept, name='abstractconcept'),

    # ## Payroll News URLs
    path('payroll/new/loans/', loans.loans, name='loans'),
    path('payroll/new/loans/edit/', loans.edit_loans, name='edit_loans'),
    path('payroll/new/disabilities/', disabilities.disabilities, name='disabilities'),
    path('payroll/new/disabilities/edit/', disabilities.edit_disabilities, name='edit_disabilities'),
    path('payroll/new/disabilities/entity/', disabilities.get_entity, name='get_entity'),
    path('payroll/vacation/historical', vacation.vacation, name='vacation'),
    path('payroll/vacation/general/', vacation_general.vacation_general, name='vacation_general'),
    path('payroll/vacation/general/data/', vacation_general.get_novedades, name='get_novedades'),
    path('payroll/vacation/balance/', vacation_balance.vacation_balance, name='vacation_balance'),
    path('payroll/vacation/balance/download/', vacation_balance.vacation_balance_download, name='vacation_balance_download'),
    path('payroll/vacation/request/', vacation_request.vacation_request, name='vacation_request'),
    path('payroll/vacation/request/get/', vacation_request.get_vacation_details, name='get_vacation_details'),
    path('payroll/vacation/request/acction/', vacation_request.get_vacation_acction, name='get_vacation_acction'),

    # ## Mass Email URL
    path('payroll/sheet/massive/mail/', payrollsheet.massive_mail, name='massivemail'),

    # ## Security URLs
    path('security/user/', loginweb.loginweb, name='loginweb'),

    ## Admin Login URL (commented out)
    
    ## Index URL
    path('', index.index_companies, name='index_companies'),
]


urlhtmxpatterns =[
    path('parameters/cost/center/add', Costcenter.costcenter_modal, name='costcenter_modal'),
    path('parameters/charges/add', charges.charges_modal, name='charges_modal'),
    path('parameters/accountin/add',accountinggroup.accountinggroup_modal , name='accountinggroup_modal'),
    path('parameters/workplace/add', workplace.workplace_modal, name='workplace_modal'),
    path('parameters/headquarters/add', headquarters.headquarters_modal, name='headquarters_modal'),

]

urlpatterns += urlhtmxpatterns  

urlunpolypatterns =[
    
    path('payroll/new/disabilities/modal', disabilities.disabilities_modal, name='disabilities_modal'),
    path('payroll/new/disabilities/modal/edit', disabilities.disabilities_modal_edit, name='disabilities_modal_edit'),

]

urlpatterns += urlunpolypatterns  

nomiweb/urls.py
from django.contrib import admin
from django.urls import path ,include
from apps.login.views import custom_400 ,custom_403,custom_404 ,custom_500
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

# Importa Django Debug Toolbar solo si DEBUG está activado
if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('', include(('apps.login.urls', 'login'))),
    path('accounts/', include('allauth.urls')),
    path('', include('allauth.socialaccount.urls')),
    #path('contable/', include(('apps.payroll.urls', 'payroll'))),
    path('employees/', include(('apps.employees.urls', 'employees'))),
    path('companies/', include(('apps.companies.urls', 'companies'))),
    path('admin/', include(('apps.administrator.urls', 'admin'))),
    path('payroll/', include(('apps.payroll.urls', 'payroll'))),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Si DEBUG está activado, agrega las URLs de Django Debug Toolbar
if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

#handler400 = custom_400  # Configura la vista custom_400 para manejar el error 400
#handler403 = custom_403  # Configura la vista custom_403 para manejar el error 403
handler404 = 'apps.login.views.custom_404' # Configura la vista custom_404 para manejar el error 404
handler500 = 'apps.login.views.custom_500'  # Configura la vista custom_500 para manejar el error 500

apps/companies/forms/accountinggroupForm.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from apps.common.models import Nivelesestructura
from django.urls import reverse

class accountinggroupForm(forms.Form):
    grupo = forms.CharField(label='Nombre del Grupo',max_length=2, widget=forms.TextInput(attrs={'placeholder': 'Ingrese el nombre del grupo'}))
    grupocontable = forms.CharField(label='Grupo Contable' , widget=forms.TextInput(attrs={'placeholder': 'Grupo Contable'}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'form_accountinggroup'
        self.helper.enctype = 'multipart/form-data'
        
        
        self.helper.attrs.update({
            'hx-post': reverse('companies:accountinggroup_modal'),  # Usa el nombre de la vista en urls.py
            'hx-target': '#modal-container',  # El elemento donde se actualizará el contenido
            'hx-swap': 'innerHTML',  # Cómo se actualizará el contenido del objetivo
        })
        
        self.helper.layout = Layout(
            Row(
                Column('grupo', css_class='form-group mb-0'),
                Column('grupocontable', css_class='form-group mb-0'),
                css_class='row'
            ),
        )
    
    def clean_grupo(self):
        grupo = self.cleaned_data.get('grupo')
        if len(grupo) > 2:
            raise forms.ValidationError('El nombre del grupo no puede tener más de 2 caracteres.')
        return grupo
    

apps/companies/forms/workplaceForm.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from apps.common.models   import Contabgrupos
from django.urls import reverse

# class Centrotrabajo(models.Model):
#     nombrecentrotrabajo = models.CharField(max_length=30, blank=True, null=True)
#     tarifaarl = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
# 

class workplaceForm(forms.Form):
    
    TARIFA_CHOICES = [
        ('', '---------'),
        ('0.522', 'Riesgo  mínimo (Clase I) - 0.522'),
        ('1.044', 'Riesgo  bajo (Clase II) - 1.044'),
        ('2.436', 'Riesgo medio (Clase III) - 2.436'),
        ('4.350', 'Riesgo alto (Clase IV) - 4.350'),
        ('6.960', 'Riesgo máximo (Clase V) - 6.960'),
    ]
    
    nombrecentrotrabajo = forms.CharField(label='Nombre de Costo' , required=True ,widget=forms.TextInput(attrs={'placeholder': 'nombre de centro trabajo'}))
    tarifaarl = forms.ChoiceField(choices=TARIFA_CHOICES , label='Tarifa ARL' , required=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_id = 'form_charge'
        self.helper.enctype = 'multipart/form-data'
        
        
        self.helper.attrs.update({
            'hx-post': reverse('companies:workplace_modal'),  # Usa el nombre de la vista en urls.py
            'hx-target': '#modal-container',  # El elemento donde se actualizará el contenido
            'hx-swap': 'innerHTML',  # Cómo se actualizará el contenido del objetivo
        })
        
        self.fields['tarifaarl'].widget.attrs.update({
            'data-control': 'select2',
            'data-tags': 'true',
            'class': 'form-select',
            'data-dropdown-parent': '#conceptsModal',
            'data-hide-search': "true",
        })
        
        
        self.helper.layout = Layout(
            Row(
                Column('nombrecentrotrabajo', css_class='form-group mb-0'),
                Column('tarifaarl', css_class='form-group mb-0'),
                css_class='row'
            ),
        )
    

apps/companies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contratos , Contratosemp ,Costos , Tipocontrato , Centrotrabajo
import locale



def startCompanies(request): 
    combined_data = {}
    
    contracts = Contratos.objects.using("lectaen").filter(estadocontrato=1).values_list('cargo', 'fechainiciocontrato', 'salario', 'idcosto', 'tipocontrato', 'centrotrabajo', 'idempleado')
    
    employee_ids = set(contract[-1] for contract in contracts)
    employees = Contratosemp.objects.using("lectaen").filter(idempleado__in=employee_ids).values_list('idempleado', 'docidentidad', 'pnombre', 'papellido', 'sapellido')
    
    costs = Costos.objects.using("lectaen").all().values_list('idcosto', 'nomcosto')
    tipo_contrato = Tipocontrato.objects.using("lectaen").all().values_list('idtipocontrato', 'tipocontrato')
    centrotrabajo = Centrotrabajo.objects.using("lectaen").all().values_list('tarifaarl', 'centrotrabajo')
    
    for employee_id in employee_ids:
        combined_data[employee_id] = {'docidentidad': None, 'pnombre': None, 'papellido': None, 'sapellido': None, 'contratos': [], 'costs': {'idcosto': None, 'nomcosto': None}, 'tipo_contrato': None}

    for contract in contracts:
        employee_id = contract[-1]
        combined_data[employee_id]['contratos'].append(contract[:-1])

    for employee_detail in employees:
        employee_id = employee_detail[0]
        combined_data[employee_id]['docidentidad'] = employee_detail[1]
        combined_data[employee_id]['pnombre'] = employee_detail[2]
        combined_data[employee_id]['papellido'] = employee_detail[3]
        combined_data[employee_id]['sapellido'] = employee_detail[4]
    
    
    for employee_id, employee_data in combined_data.items():
        contratos_formateados = []
        for contract in employee_data['contratos']:
            salario_formateado = "{:,.0f}".format(contract[2])
            contrato_formateado = (*contract[:2], salario_formateado, *contract[3:])
            contratos_formateados.append(contrato_formateado)
        combined_data[employee_id]['contratos'] = contratos_formateados



    for employee_id, employee_data in combined_data.items():
        for contract in employee_data['contratos']:
            tipo_contrato_contract = contract[4]  
            for tipo in tipo_contrato:
                if tipo[0] == int(tipo_contrato_contract): 
                    combined_data[employee_id]['tipo_contrato'] = tipo[1]
                    break
            else:
                continue
            break 
    
    for employee_id, employee_data in combined_data.items():
        for contract in employee_data['contratos']:
            centrotrabajo_contract = contract[5]  
            for centro in centrotrabajo:
                if centro[1] == int (centrotrabajo_contract): 
                    combined_data[employee_id]['centrotrabajo'] = centro[0]
                    break
            else:
                continue
            break
    
    return render(request, './companies/index.html', {'combined_data': combined_data})

templates/companies/partials/accountinggroupModal.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" id="conceptsModal" name="conceptsModal" tabindex="-1" aria-labelledby="conceptsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-dialog-scrollable modal-lg">
        <div class="modal-content" id="modal-container">
            <div class="modal-header">
                <h5 class="modal-title" id="conceptsModalLabel">Nuevo Grupo</h5>
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()" >
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% crispy form %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal" onclick="closeModal()" >Cerrar</button>
                <button type="submit" form="form_accountinggroup" class="btn btn-light-info">Crear</button>
            </div>
        </div>
    </div>
</div>


<script>

function closeModal(reload = false) {
    var modals = document.querySelectorAll('.modal.show');
    var backdrops = document.querySelectorAll('.modal-backdrop');

    modals.forEach(modalEl => {
        var modal = bootstrap.Modal.getInstance(modalEl);
        if (modal) {
            modal.hide();
        }
    });

    backdrops.forEach(backdrop => backdrop.remove());

    // Limpiar el contenido del modal si aplica
    document.getElementById('modal-container').innerHTML = '';

    // Recargar la página si se solicita
    if (reload) {
        window.location.reload();
    }
} 

$(document).ready(function () {
    // Inicializa Select2 para los campos

    $('#id_nivelcargo').select2({
        dropdownParent: $('#conceptsModal'),
        minimumResultsForSearch: -1,
    });
});


document.body.addEventListener('htmx:afterRequest', function(evt) {
    if (evt.detail.successful) {
        var response = evt.detail.xhr.responseText;
        // Verificar si la respuesta es un JSON con estado de éxito
        try {
            var responseJson = JSON.parse(response);
            
            if (responseJson.status === 'success') {
                var modal = bootstrap.Modal.getInstance(document.getElementById('conceptsModal'));
                var modalBackdrop = document.querySelector('.modal-backdrop');
                
                if (modal) {
                    modal.hide(); // Cierra el modal después de una respuesta exitosa
                }

                if (modalBackdrop) {
                    modalBackdrop.remove(); // Elimina el fondo modal residual
                }

                // Mostrar el Swal de éxito
                Swal.fire({
                    text: responseJson.message, // Mensaje de éxito
                    icon: "success",  
                    showConfirmButton: true,
                    confirmButtonText: "Ok",
                    customClass: {
                        confirmButton: "btn btn-primary"
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.reload();  // Recarga la página
                    }
                });

            } else {
                
            }
        } catch (e) {
            
        }
    }
});
</script>

templates/companies/partials/costcenterModal.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" id="conceptsModal" name="conceptsModal" tabindex="-1" aria-labelledby="conceptsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-dialog-scrollable modal-lg">
        <div class="modal-content" id="modal-container">
            <div class="modal-header">
                <h5 class="modal-title" id="conceptsModalLabel">Nuevo Centro de Costos</h5>
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()" >
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% crispy form %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal" onclick="closeModal()" >Cerrar</button>
                <button type="submit" form="form_costcenter" class="btn btn-light-info">Crear</button>
            </div>
        </div>
    </div>
</div>


<script>

function closeModal(reload = false) {
    var modals = document.querySelectorAll('.modal.show');
    var backdrops = document.querySelectorAll('.modal-backdrop');

    modals.forEach(modalEl => {
        var modal = bootstrap.Modal.getInstance(modalEl);
        if (modal) {
            modal.hide();
        }
    });

    backdrops.forEach(backdrop => backdrop.remove());

    // Limpiar el contenido del modal si aplica
    document.getElementById('modal-container').innerHTML = '';

    // Recargar la página si se solicita
    if (reload) {
        window.location.reload();
    }
} 
    

$(document).ready(function () {
    // Inicializa Select2 para los campos
    $('#id_grupocontable').select2({
        dropdownParent: $('#conceptsModal'),
        minimumResultsForSearch: -1,
        
    });

});


document.body.addEventListener('htmx:afterRequest', function(evt) {
    if (evt.detail.successful) {
        var response = evt.detail.xhr.responseText;
        // Verificar si la respuesta es un JSON con estado de éxito
        try {
            var responseJson = JSON.parse(response);
            if (responseJson.status === 'success') {
                var modal = bootstrap.Modal.getInstance(document.getElementById('conceptsModal'));
                var modalBackdrop = document.querySelector('.modal-backdrop');
                
                if (modal) {
                    modal.hide(); // Cierra el modal después de una respuesta exitosa
                }
                if (modalBackdrop) {
                    modalBackdrop.remove(); // Elimina el fondo modal residual
                }
                // Mostrar el Swal de éxito
                Swal.fire({
                    text: responseJson.message, // Mensaje de éxito
                    icon: "success",  
                    showConfirmButton: true,
                    confirmButtonText: "Ok",
                    customClass: {
                        confirmButton: "btn btn-primary"
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.reload();  // Recarga la página
                    }
                });

            } else {
                
            }
        } catch (e) {
            
        }
    }
});
</script>

templates/companies/partials/create_disabilities_modal.html
{% load crispy_forms_tags %}
<!-- Bootstrap-styled modal -->
<div class="modal-content"  id="modal-content">
    <div class="modal-header">
        <h5 class="modal-title"> Nueva Incapacidad</h5>
        <!--begin::Close-->
        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" up-dismiss aria-label="Close">
            <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
        </div>
        <!--end::Close-->
    </div>   
    <div class="separator my-5"></div> 
    <!--begin::Input group-->        
    <div class="modal-body">

        <div class="container">
            <div class="row align-items-start">
                {% csrf_token %}
                {% crispy form %}
            </div>   
        </div>

    </div>
    <div class="separator my-5"></div>
    <div class="modal-footer btn-group">
        <button type="button" class="btn btn-light-secondary"  up-dismiss>Cancelar</button>
        <div style="width: 10px;"></div>
        <button type="submit" class="btn btn-light-info" form="form_disablities" >Guardar Incapacidad</button>
    </div>
</div>

templates/companies/partials/create_disabilities_modal_edit.html
{% load crispy_forms_tags %}
<!-- Bootstrap-styled modal -->
<div class="modal-content"  id="modal-content">
    <div class="modal-header">
        <h5 class="modal-title"> Edicion de Incapacidad # </h5>
        <!--begin::Close-->
        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" up-dismiss aria-label="Close">
            <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
        </div>
        <!--end::Close-->
    </div>   
    <div class="separator my-5"></div> 
    <!--begin::Input group-->        
    <div class="modal-body">

        <div class="container">
            <div class="row align-items-start">
                {% csrf_token %}
                {% crispy form %}
            </div>   
        </div>

    </div>
    <div class="separator my-5"></div>
    <div class="modal-footer btn-group">
        <button type="button" class="btn btn-light-secondary"  up-dismiss>Cancelar</button>
        <div style="width: 10px;"></div>
        <button type="submit" class="btn btn-light-info" form="form_disablities" >Actualizar Incapacidad</button>
    </div>
</div>

templates/companies/partials/workplaceModal.html
{% load crispy_forms_tags %}
<!-- Modal -->
<div class="modal fade" id="conceptsModal" name="conceptsModal" tabindex="-1" aria-labelledby="conceptsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-dialog-scrollable modal-lg">
        <div class="modal-content" id="modal-container">
            <div class="modal-header">
                <h5 class="modal-title" id="conceptsModalLabel">Nuevo Centro de trabajo</h5>
                <!--begin::Close-->
                <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()" >
                    <i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i>
                </div>
                <!--end::Close-->
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% crispy form %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal" onclick="closeModal()" >Cerrar</button>
                <button type="submit" form="form_charge" class="btn btn-light-info">Crear</button>
            </div>
        </div>
    </div>
</div>


<script>

function closeModal(reload = false) {
    var modals = document.querySelectorAll('.modal.show');
    var backdrops = document.querySelectorAll('.modal-backdrop');

    modals.forEach(modalEl => {
        var modal = bootstrap.Modal.getInstance(modalEl);
        if (modal) {
            modal.hide();
        }
    });

    backdrops.forEach(backdrop => backdrop.remove());

    // Limpiar el contenido del modal si aplica
    document.getElementById('modal-container').innerHTML = '';

    // Recargar la página si se solicita
    if (reload) {
        window.location.reload();
    }
} 

$(document).ready(function () {
    // Inicializa Select2 para los campos

    $('#id_tarifaarl').select2({
        dropdownParent: $('#conceptsModal'),
        minimumResultsForSearch: -1,
    });
});


document.body.addEventListener('htmx:afterRequest', function(evt) {
    if (evt.detail.successful) {
        var response = evt.detail.xhr.responseText;
        // Verificar si la respuesta es un JSON con estado de éxito
        try {
            var responseJson = JSON.parse(response);
            
            if (responseJson.status === 'success') {
                var modal = bootstrap.Modal.getInstance(document.getElementById('conceptsModal'));
                var modalBackdrop = document.querySelector('.modal-backdrop');
                
                if (modal) {
                    modal.hide(); // Cierra el modal después de una respuesta exitosa
                }

                if (modalBackdrop) {
                    modalBackdrop.remove(); // Elimina el fondo modal residual
                }

                // Mostrar el Swal de éxito
                Swal.fire({
                    text: responseJson.message, // Mensaje de éxito
                    icon: "success",  
                    showConfirmButton: true,
                    confirmButtonText: "Ok",
                    customClass: {
                        confirmButton: "btn btn-primary"
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.reload();  // Recarga la página
                    }
                });

            } else {
                
            }
        } catch (e) {
            
        }
    }
});
</script>